version: '3.1'

services:
  db:
    container_name: distro-db
    image: mongo
    restart: unless-stopped
    volumes:
      - distrodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
  db-adminer:
    container_name: distro-db-adminer
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@db:27017/
  cache:
    container_name: distro-cache
    image: redis
    restart: unless-stopped
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - distrocache:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  cache-adminer:
    container_name: distro-cache-adminer
    image: redislabs/redisinsight
    restart: unless-stopped
    ports:
      - 8001:8001

volumes:
  distrodb:
  distrocache: